### DISCUSSION TITLE
Physiology Mapping Functions

### DISCUSSION THREAD

**Discussion by awatson1978** [synthetichealth/synthea#1348] [Ideas]
With the new physiology models being introduced into Synthea, we have a need for some documentation around the physiology mapping functions.  I originally described this as "write[ing] an expression that intersects the sine wave to create periods of sleep/awake".  But instead of doing the optimizations ourselves, we will be leaving it as an exercise to the user to adjust the mapping functions for their specific use case.  The following is proposed documentation notes to be included in the Wiki:

### Physiology Generator Inputs/Outputs
Each of the new physiology models is managed by a generator function, which handles inputs and outputs into the set of partial differential equations contained within the model.  Example input and outputs looks like the following:

```yml
inputs:
#  # Effects of age and BMI loosely estimated from a comprehensive study on adult blood pressure
#  # percentiles (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4553889/)
#  # More research is needed to determine appropriate age / BMI effects on all model parameters.
 - fromExp: "1.1889 + 0.025 * (#{BMI} - 21.7) + (if #b{blood_pressure_controlled} then 0 else (0.0112 * #{age}))"
   to: R_sys
   variance: 0.25 # Allowable variance in input to avoid running simulation
   
outputs:
 - fromExp: "((Max(#{V_lv}) - Min(#{V_lv})) / Max(#{V_lv}))*100"
   to: Left ventricular Ejection fraction
```

Users of Synthea who wish to customize and optimize these physiology models to their use cases are encouraged to look at the `fromExp` field, which contains a mapping function that can be optimized for particular use cases.  In particular, we note the following functionalities that users should be aware of:

- It is possible to pull in variables from the patient medical chart, using the `#{foo}` syntax.
- Basic `if then else` functionality is supported within the expressions.
- Functions are supported within the equations, as demonstrated by the `Max() and Min()` functions.  
- The functions map between parameters in the partial differential equations and variables in the patient record via the `to` field.

With this syntax and grammar, motivated users can optimize these physiology functions to produce daily activity patterns that the simulated patients follow, such as taking medications each day, exercising, or other behaviors.  Seasonal trends can be developed.  Acute response to emergencies and accidents can be modeled.  And so forth.  

### Intersecting the Graph
It's important to understand that the physiology models produce continuous theoretical data for the patient over a discrete time period.  This data is `not` the kind of data that would be generated by any particular medical device or wearable; rather, these models describe a theoretical representation of the biological functions going on within a person; of which a medical device or wearable will take a discrete snapshot at any particular time.  

To put it in calculus terms, these models represent continuous functions; and any particular clinical observation will be a derivative function at a specific moment in time.  

To visualize this, imaging the circadian cycle; which is roughly timed with the human sleep/wake cycle.  Physiologically, this cycle is generally measured by melatonin and cortisol levels, which are increasing and decreasing throughout the day.  

![circadian_clock_1](https://github.com/synthetichealth/synthea/assets/675910/6a614e8a-0c66-450d-9106-b96ea012a85c)

At certain thresholds, these melatonin and cortisol levels impact a person's natural sleep cycle, in both the time of day they go to sleep, and the length of sleep.  We can represent that with an intersecting function, like so.  
![circadian_clock_2](https://github.com/synthetichealth/synthea/assets/675910/daaf06f4-3cad-4198-ab83-ccbf488d2746)

And what we're seeking with these optimized functions, is to take our continuous theoretical function, and filter it, such that it produces the same data that we might obtain from an empirical clinical measurement.  So, for instance, wearing an iWatch with a sleep tracking app, might generate the following data:
![circadian_clock_3](https://github.com/synthetichealth/synthea/assets/675910/fc556759-ef01-4c48-9af8-7b22a1c4e67a)

Another use case for these intersecting functions, is that of setting sensitivity thresholds.  Consider the case of an ECG monitor.  In the following 10s example, we have an intersecting function that produces a count of N=7 beats per 10s, which could then be mapped to a FHIR Observation for a single vital signs measurement.    
![ecg_1](https://github.com/synthetichealth/synthea/assets/675910/92dbab80-b9d8-4f52-b5d4-a24f717332fc)

Alternatively, if we adjusting the threshold of our intersecting function, we could create a more permissive filter, with a count of N=11.  
![ecg_2](https://github.com/synthetichealth/synthea/assets/675910/1374e679-543e-4cc3-a046-737ddd863977)

Such thresholding allows us to use the physiology models in increasingly complex ways.  We may take the same model, and use it to generate physiology data:
![menstrual_cycle_1](https://github.com/synthetichealth/synthea/assets/675910/4dbd6613-03cd-47ff-9290-cef5de05f1c1)

Or, we might focus on a different part of the continuous function, and use the intersecting function to generate behavioral or mood data instead.  
![menstrual_cycle_2](https://github.com/synthetichealth/synthea/assets/675910/fad06b55-1780-4071-90a7-9ec755047017)

Similar, depending on thresholding levels, one might use a pulmonary oxygen intake model to model chest breathing vs diaphragmatic breathing.   
![pulmonary_oxygen_intake_1](https://github.com/synthetichealth/synthea/assets/675910/cf31cc83-3cc5-4872-a62a-061d3e7c55b2)

### Intersection Function
How these functions are used to represent discrete data generated by medical devices and wearables is left to the reader.  Suffice it to say that you'll want something like the following: 

```yml  
#  Melatonin levels indicating sleep levels   
outputs:
 - fromExp: "if (#{melatonin} > 1.4) then 50 else 80"
   to: heartrate
```

Or better yet, perhaps the following
```yml  
#  Melatonin levels indicating sleep levels   
outputs:
 - fromExp: "if (#{melatonin} > 1.4) then 50 else null"
   to: heartrate
```

Get creative.  Between `if/then` statements, functions, and input/output mapping, there's enough flexibility to get creative and use these physiology models to create all sorts of example wearables data.
