### DISCUSSION TITLE
How do I add multiple values to a list in a resource using Flexporter?

### DISCUSSION THREAD

**Discussion by Piyush1321** [synthetichealth/synthea#1421] [Q&A]
I'm trying to figure out how to add multiple values to a list in my code for generating an Encounter resource.
`- applicability: Encounter
  fields:
    - location: Encounter.serviceType.coding
      value:
        code: {"59400", "3424"}
        system: http://www.ama-assn.org/go/cpt
`
I want both codes to be included in the serviceType field like this:

`{
  "resourceType": "Encounter",
  "serviceType": {
    "coding": [
      {
        "code": "59400",
        "system": "http://www.ama-assn.org/go/cpt"
      },
      {
        "code": "3424",
        "system": "http://www.ama-assn.org/go/cpt"
      }
    ]
  }
}
`

How can I achieve this result using Flexporter?

**Comment by dehall** [comment]
I'm trying this out and unfortunately the options that I would consider intuitive don't seem to work, so the last resort is a bit of a hack.
This flexporter action should produce the output you're looking for:

```
 - name: testSetValues
   set_values:
     - applicability: Encounter 
       fields: 
         - location: Encounter.serviceType.coding.where(code='59400')
           value: 
             system: http://www.ama-assn.org/go/cpt
         - location: Encounter.serviceType.coding.where(code='3424')
           value: 
             system: http://www.ama-assn.org/go/cpt
```

Let me know if that doesn't work for you. In the meantime I'll see what I can do to make other more obvious approaches work. (The two options I would have preferred are 1) use two fields entries, `location: Encounter.serviceType.coding[0]` and `...[1]`; or 2)  use one entry `location: Encounter.serviceType` and the `value` is a list of the two codings)

**Reply by dehall** [reply]
Hi, apologies I forgot to update you when the feature was merged a few weeks ago. Using the latest from the master branch, these 3 approaches will now produce roughly equivalent results (only "roughly equivalent" because the order of the items may differ when using the `.where` approach). The first approach uses `.where` with a discriminator, as noted above this would work previously, the second approach uses multiple `fields` and each refers to a particular index, the third approach is that a `value` may be a list

```yml
 - name: testSetValues_where
   set_values:
     - applicability: Encounter 
       fields: 
         - location: Encounter.serviceType.coding.where(code='229')
           value: 
             system: http://terminology.hl7.org/CodeSystem/service-type
         - location: Encounter.serviceType.coding.where(code='355')
           value: 
             system: http://terminology.hl7.org/CodeSystem/service-type


 - name: testSetValues_indexed
   set_values:
     - applicability: Encounter 
       fields: 
         - location: Encounter.serviceType.coding[0]
           value: 
             system: http://terminology.hl7.org/CodeSystem/service-type
             code: "229"
         - location: Encounter.serviceType.coding[1]
           value: 
             system: http://terminology.hl7.org/CodeSystem/service-type
             code: "355"


 - name: testSetValues_list
   set_values:
     - applicability: Encounter 
       fields: 
         - location: Encounter.serviceType.coding
           value:
             - system: http://terminology.hl7.org/CodeSystem/service-type
               code: "229"
             - system: http://terminology.hl7.org/CodeSystem/service-type
               code: "355"

```
