### DISCUSSION TITLE
How to model route of administration?

### DISCUSSION THREAD

**Discussion by samrere** [synthetichealth/synthea#1423] [Q&A] [answered]
Hi!
Is there a way to model route of administration in synthea module builder?
I'm trying to model:

"Inpatient hospitalizations where an opioid antagonist was administered ... The route of administration of the opioid antagonist must be by intranasal spray, inhalation, intramuscular, subcutaneous, or intravenous injection."

suppose opioid antagonist is coded 1191222 in RxNorm vocab, and can be modeled using a MedicationOrder state, how can route of admin coded 46713006 in SNOMED vocab be modeled?

Thank you for help!

**Comment by dehall** [comment, marked as answer]
I'm assuming you're looking for FHIR output, if that's the case read on but if not, no this field is not supported and there's no way to add new fields to other output types without making changes to Synthea code. That's not impossible but it requires some level of software development expertise.

For FHIR: Route of administration isn't one of the fields that is natively supported in Synthea, so this is an instance where you might find the "Flexporter" useful. https://github.com/synthetichealth/synthea/wiki/Flexporter
Instead of representing this in the module builder, you would create an additional file with instructions that mean "add this field to resources that meet this criteria"

From a quick search there are two places in FHIR where you may want to represent route of administration (possibly more than two but these two are likely the best fit): [MedicationAdministration.dosage.route](http://hl7.org/fhir/R4/medicationadministration-definitions.html#MedicationAdministration.dosage.route)  and [MedicationRequest.dosageInstruction](http://hl7.org/fhir/R4/medicationrequest-definitions.html#MedicationRequest.dosageInstruction) -> [.route](http://hl7.org/fhir/R4/dosage-definitions.html#Dosage.route) 
Let's stick with the MedicationAdministration for the moment but the same principle could be used for the MedicationRequest

The example below defines a mapping file where it looks for MedicationAdministration with the code '1191222', and populates the dosage.route with the SNOMED code 46713006

```yaml
name: Route of administration

# applicability determines whether this mapping applies to a given file
applicability: true

actions:
 - name: Route of administration
   set_values:
     - applicability: MedicationAdministration.medication.coding.where($this.code = '1191222')
       fields: 
         - location: MedicationAdministration.dosage.route.coding
           value: 
             system: http://snomed.info/sct
             code: "46713006"
             display: "Nasal use"
```

Save this as `route_admin.yml` or whatever name you like, then to use it, run `./run_synthea -fm route_admin.yml [...other settings]`

After that, any instances of a MedicationAdministration with that code should have that `route` set, for example:


```json
    {
      "resourceType": "MedicationAdministration",
      "id": "be5f502e-b4c2-3e1b-e149-d2cdb5750687",
      "status": "completed",
      "medicationCodeableConcept": {
        "coding": [ {
          "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
          "code": "1191222",
          "display": "naloxone hydrochloride 0.4 MG/ML Injectable Solution"
        } ],
        "text": "naloxone hydrochloride 0.4 MG/ML Injectable Solution"
      },
      "subject": {
        "reference": "urn:uuid:ec6b8c06-433f-11fa-1c84-878e76fbfd48"
      },
      "context": {
        "reference": "urn:uuid:552f860d-377f-c156-3a4d-7f7ceb48c3dd"
      },
      "effectiveDateTime": "2015-02-28T10:42:19-05:00",
      "reasonReference": [ {
        "reference": "urn:uuid:0a3c808a-c7c9-915e-70db-4fdbf0bda951",
        "display": "Drug overdose (disorder)"
      } ],
      "dosage": {
        "route": {
          "coding": [ {
            "system": "http://snomed.info/sct",
            "code": "46713006",
            "display": "Nasal use"
          } ]
        }
      }
    }
```


Let me know if this doesn't work
