### DISCUSSION TITLE
How to use randomCode Functions with Flexporter

### DISCUSSION THREAD

**Discussion by Sharath314e** [synthetichealth/synthea#1424] [Q&A] [answered]
I want to use [ValuesetURL](https://r4.ontoserver.csiro.au/fhir/ValueSet/2.16.840.1.113883.3.464.1003.101.12.1001) to load code, system and display into Flexporter fields using the provided randomCode function. When I try to use this I get Error or NullPointerException. Can anyone help me to fix this issue.

**Comment by dehall** [comment]
Can you share the mapping file that you're using? I can take a look and see where it's going wrong. The flexporter is still very experimental so it's possible the feature may need to be improved

**Reply by Sharath314e** [reply]
`applicability: true
actions:
  - name: DenominatorExclusion1
    set_values:
      - applicability: Encounter
        fields:
          - location: Encounter.type.coding
            value: $randomCode("https://r4.ontoserver.csiro.au/fhir/ValueSet/2.16.840.1.113883.3.666.5.307")
          - location: period
            value:
              start: "2023-01-28T03:37:51+00:00"
              end: "2023-01-29T03:37:51+00:00"`

Here I am trying to populate the values for encounter.type.coding from the valueset, but I get a nullpointerException.

**Reply by dehall** [reply, marked as answer]
Ah ok thanks, that all looks like it should work but as I debug this I see some ways we need to improve our documentation and could potentially make some things simpler.

The short version is, you will need to make sure the `generate.terminology_service_url` setting is set, either by uncommenting it in `src/main/resources/synthea.properties` or by providing the argument on the command line `--generate.terminology_service_url "https://r4.ontoserver.csiro.au/fhir"`, and then use the following mapping:

```yaml
 - name: DenominatorExclusion1
   set_values:
     - applicability: Encounter
       fields:
         - location: Encounter.type.coding
           value: $randomCode([http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113883.3.666.5.307])
         - location: period
           value:
              start: "2023-01-28T03:37:51+00:00"
              end: "2023-01-29T03:37:51+00:00"
```

The necessary changes were as follows:
 - Arguments to value functions such as `$randomCode` need to be wrapped in square braces `[]` even if only a single value
 - Arguments to value functions should not have quotes
 - The URL to provide here should be the official URL of the ValueSet, not the url on terminology server to fetch from. (In this case I just went to the URL https://r4.ontoserver.csiro.au/fhir/ValueSet/2.16.840.1.113883.3.666.5.307 and found the URL property in the description)

In the short term I'll update our documentation to make these clearer. I'll also put a note to simplify some of these requirements, for example the quotes shouldn't be an issue and the [] maybe shouldn't be necessary.
