### ISSUE TITLE
Observations with referenceRange and Interpretation

### ISSUE THREAD

**Issue by jdelucaa** [synthetichealth/synthea#731]
I use Synthea to generate some laboratory and vital signs observations, but I don't see the [referenceRange](https://www.hl7.org/fhir/observation-definitions.html#Observation.referenceRange) neither the [interpretation](https://www.hl7.org/fhir/observation-definitions.html#Observation.interpretation) being generated for those observations.

How can I have observations with that content included?

Thanks in advance.

**Comment by jawalonoski** [comment]
@jdelucaa That is not currently a supported option.

Theoretically, a change could be implemented that would fill out some of the reference ranges using the [biometrics.yml](https://github.com/synthetichealth/synthea/blob/master/src/main/resources/biometrics.yml) file, but that would not be comprehensive. 

I'm not sure there is an easy path towards populating interpretation.

**Comment by jdelucaa** [comment]
Hey @jawalonoski, thanks for the answer.

Should I close this issue?

**Comment by jawalonoski** [comment]
Let's leave it open for now. Maybe this will be addressed in the future and this tracks the issue.

**Comment by TerriblyVexed** [comment]
I am also having the same issue. This functionality interests me very much.
@jawalonoski could you expound on your theory? I have followed what you intend conceptually but am unable to figure out how to implement it. Is it just a matter of adding lines in the YAML file for low, high, etc.? Specifically for BP.
As in
`metabolic:
  blood_pressure:
    normal:
      systolic: [100,139] # mmHg
      diastolic: [70,89]  # mmHg
    hypertensive:
      systolic: [140,160,200] # mmHg
      diastolic: [90,120] # mmHg
    low:
      systolic: [99,0] #mmHg
      diastolic: [69,0] #mmHg
    high:
      systolic: [140,200] #mmHg
      diastolic: [90,120] #mmHg`

Are there other changes that would need to be made? Like to BiometricsConfig.java and BloodPressureValueGenerator.java?
Or would it require a completely new class (like BloodPressureReferenceRangeGenerator.java)?

**Comment by jawalonoski** [comment]
Currently, the `biometrics.yml` file has ranges that are _used_ for vital signs. The thought was to add `reference ranges` to this list. So, for example:

```yaml
metabolic:
  blood_pressure:
    normal:
      systolic: [100,139] # mmHg
      diastolic: [70,89]  # mmHg
    hypertensive:
      systolic: [140,160,200] # mmHg
      diastolic: [90,120] # mmHg
    reference: # new section
      systolic: [100, 120] # made up range
      diastolic: [70,90] # made up range
```

That is probably a bad example though, because I'm not sure reference ranges are typically used for blood pressure.

Instead, they are more useful for lab results, e.g. White Blood Cell counts in a Blood Panel, Amino Acids in a Urine Panel, that sort of thing.

One problem: where do all these references ranges come from?

A second problem: how do you encode them in Synthea?

A third problem: how do you match them observations or panels in the modules and the exporters?
